:icons: font
:numbered:
ifdef::env-github[:outfilesuffix: .adoc]

ifdef::env-github,env-browser[]
// Exibe ícones para os blocos como NOTE e IMPORTANT no GitHub
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= AsciiDoctor GitHub Pages Action

ifdef::env-github[image:https://github.com/manoelcampos/asciidoctor-ghpages-action/workflows/asciidoctor-ghpages/badge.svg[GitHub Pages,link=http://manoelcampos.com/asciidoctor-ghpages-action/]]

A GitHub Action for your CI workflow that recursively converts every `adoc` file to `html`, renaming resulting `README.html` to `index.html` then pushing all generated html and existing files to the `gh-pages` branch. It also keeps only the latest commit on the `gh-pages` branch, stoping it to grow too much. 

After configuring the action, your GitHub Pages will be available at `http&#58;//your-username.github.io/your-repository`.

ifdef::env-github[]
== Live Demo

We taste our own medicine by publishing this reposiroty in http://manoelcampos.com/asciidoctor-ghpages-action/[GitHub Pages].
endif::[]

ifndef::env-github[]
== Project on GitHub

View the https://github.com/manoelcampos/asciidoctor-ghpages-action[project on GitHub] and take the chance to give it a star.
endif::[]

== Configuration

You have to just add the action to your yml workflow file and that is it.
You can optionally customize the build by giving extra parameters to
the action, which will be handed to the asciidoctor tool.

You can check a complete https://github.com/manoelcampos/asciidoc-github-template/blob/master/.github/workflows/asciidoctor-ghpages.yml[workflow file here].

=== Building an e-book

The action allows enabling the automatic generation of an `ebook.pdf` file from the AsciiDoc files. The pdf is pushed to the `gh-pages` branch too.
To enable that, just add the following configuration:

[source, yml]
----
pdf_build: true
----

ifdef::env-github,env-browser[]
A sample PDF ebook is https://github.com/manoelcampos/asciidoctor-ghpages-action/blob/gh-pages/ebook.pdf[available here].
endif::[]

ifndef::env-github,env-browser[]
IMPORTANT: An always updated version of this ebook is https://github.com/manoelcampos/asciidoctor-ghpages-action/blob/gh-pages/ebook.pdf[available here].
endif::[]

=== AsciiDoctor Reveal.js Slides

You can also build https://github.com/asciidoctor/asciidoctor-reveal.js/[AsciiDoctor Reveal.js] slides with this action.
That will generate a slides.html file into the `gh-pages` branch. You can use the following configuration for that:

- `slides_build: boolean` - enables building a slides.html file (default false)
- `slides_main_adoc_file: string` - defines the name of the AsciiDoc source file to build the slides (default 'README'). **Do not include the file extension.**
- `slides_skip_asciidoctor_build: boolean` -  to enable skippig the build of regular html files using the asciidoctor command, if you just want to generate the slides (default false)
