:icons: font
ifdef::env-github[:outfilesuffix: .adoc]

ifdef::env-github,env-browser[]
// Exibe ícones para os blocos como NOTE e IMPORTANT no GitHub
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= AsciiDoctor GitHub Pages Action

ifdef::env-github[image:https://github.com/manoelcampos/asciidoctor-ghpages-action/workflows/asciidoctor-ghpages/badge.svg[GitHub Pages,link=http://manoelcampos.com/asciidoctor-ghpages-action/]]

A GitHub Action for your CI workflow that recursively converts every `adoc` file to `html`, renaming resulting `README.html` to `index.html` then pushing all generated html and existing files to the `gh-pages` branch. It also keeps only the latest commit on the `gh-pages` branch, stoping it to grow too much. 

After configuring the action, you GitHub Pages will be available at `http://your-username.github.io/your-repository`.

ifdef::env-github[]
== Live Demo

We taste our own poison by publishing this reposiroty in http://manoelcampos.com/asciidoctor-ghpages-action/[GitHub Pages].
endif::[]

== Configuration

The action currently requires no extra configuration. You have to just add it to your yml workflow file and that is it.
You can check a basic https://github.com/manoelcampos/asciidoc-github-template/blob/master/.github/workflows/asciidoctor-ghpages.yml[workflow file here].
